services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-backend
    hostname: vault-server
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - vault-network

networks:
  vault-network:
    external: true
