services:
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    container_name: vault-mailserver
    hostname: vault-mailserver
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - vault-network
    profiles:
      - mail

networks:
  vault-network:
    external: true
